# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('move', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codebot1', models.ForeignKey(db_column='codebot1', on_delete=django.db.models.deletion.CASCADE, related_name='match_codebot1', to='gameservice.CodeBot')),
                ('codebot2', models.ForeignKey(db_column='codebot2', on_delete=django.db.models.deletion.CASCADE, related_name='match_codebot2', to='gameservice.CodeBot')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='runner',
            field=models.ForeignKey(db_column='runner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_runner', to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(db_column='winner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='history',
            name='match',
            field=models.ForeignKey(db_column='match', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Match'),
        ),
        migrations.AddField(
            model_name='codebot',
            name='player',
            field=models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Player'),
        ),
    ]
