# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebot',
            name='lang',
            field=models.CharField(choices=[('python', 'python')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
