# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('move_played', models.TextField()),
                ('contest', models.ForeignKey(db_column='contest', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('language', models.CharField(choices=[('python', 'python')], default='python', max_length=10)),
                ('player', models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Player')),
            ],
        ),
        migrations.AddField(
            model_name='contesthistory',
            name='player',
            field=models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='contest',
            name='runner',
            field=models.ForeignKey(db_column='runner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_runner', to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='contest',
            name='submission1',
            field=models.ForeignKey(db_column='submission1', on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission1', to='gameservice.Submission'),
        ),
        migrations.AddField(
            model_name='contest',
            name='submission2',
            field=models.ForeignKey(db_column='submission2', on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission2', to='gameservice.Submission'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(db_column='winner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_winner', to='gameservice.Player'),
        ),
    ]
