# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField()),
                ('starter', models.CharField(choices=[('Player1', 'Player1'), ('Player2', 'Player2')], default='Player1', max_length=10)),
                ('winner', models.CharField(choices=[('Player1', 'Player1'), ('Player2', 'Player2')], max_length=10, null=True)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_played', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('contest', models.ForeignKey(db_column='contest', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('starter', models.TextField()),
                ('umpire', models.TextField()),
                ('language', models.CharField(choices=[('python', 'python')], default='python', max_length=10)),
                ('creation_time', models.DateTimeField()),
                ('max_moves', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('language', models.CharField(choices=[('python', 'python')], default='python', max_length=10)),
                ('creation_time', models.DateTimeField()),
                ('player', models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Player')),
            ],
        ),
        migrations.AddField(
            model_name='contesthistory',
            name='player',
            field=models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.CASCADE, to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='contest',
            name='player1',
            field=models.ForeignKey(db_column='player1', on_delete=django.db.models.deletion.CASCADE, related_name='contest_player1', to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='contest',
            name='player2',
            field=models.ForeignKey(db_column='player2', on_delete=django.db.models.deletion.CASCADE, related_name='contest_player2', to='gameservice.Player'),
        ),
        migrations.AddField(
            model_name='contest',
            name='submission1',
            field=models.ForeignKey(db_column='submission1', on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission1', to='gameservice.Submission'),
        ),
        migrations.AddField(
            model_name='contest',
            name='submission2',
            field=models.ForeignKey(db_column='submission2', on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission2', to='gameservice.Submission'),
        ),
    ]
